name: Zowe CICS Main CI

on:
  push:
    paths:
      - packages/**
  pull_request:
    paths:
      - packages/**
  workflow_dispatch:

jobs:
  test:
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')
    runs-on: ${{ matrix.os }}
    outputs:
      npm-resolutions: ${{ steps.npm-update.outputs.result }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]
        os: [windows-latest, ubuntu-latest, macos-latest]

    env:
      OS: ${{ matrix.os }}
      NODE: ${{ matrix.node-version }}
      NODE_OPTIONS: --max_old_space_size=4096

    timeout-minutes: 60

    concurrency:
      group: ${{ matrix.os }}-node-${{ matrix.node-version }}-ci-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Disable Lint Annotations
      run: |
        echo "::remove-matcher owner=eslint-compact::"
        echo "::remove-matcher owner=eslint-stylish::"

    - name: Install Dependencies
      run: npm ci

    - name: Build Source
      id: build
      run: npm run build

    - name: Unit Tests
      if: ${{ always() && steps.build.outcome == 'success' }}
      run: npm run test:unit

    - name: Archive Results
      if: ${{ always() && steps.build.outcome == 'success' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.node-version }}-results
        path: packages/*/__tests__/__results__/

    - name: Upload Results to Codecov
      uses: codecov/codecov-action@v3
      with:
        env_vars: OS,NODE

    - name: Bundle all packages
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '18.x'
      run: npm run package

    - name: Archive all packages
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '18.x'
      uses: actions/upload-artifact@v3
      with:
        name: zowe-cics-client
        path: dist/*
